---
 - name: ensure python is installed and ready for use
   tags: install
   block:
   - name: install dev tools
     ansible.builtin.yum:
       name: "@Development tools"
       state: present
   - name: install additional packages
     ansible.builtin.yum:
       name:
         - libffi-devel
         - zlib-devel
         - bzip2-devel
         - openssl-devel
         - ncurses-devel
         - sqlite-devel
         - readline-devel
         - tk-devel
         - gdbm-devel
         - db4-devel
         - libpcap-devel
         - xz-devel
         - expat-devel
   - name: download python
     get_url: 
       url: '{{ python_url }}'
       dest: '{{ python_dest }}'
   - name: unarchive python on remote host
     unarchive:
       src: '{{ python_dest }}/Python-3.7.2.tar.xz'
       dest: '{{ python_dest }}'
       remote_src: yes
   - name: copy install script
     copy:
       src: scripts/install.sh
       dest: '{{ python_dest }}'
       owner: root
       group: root
       mode: 0755
   - name: install python
     shell: '{{ python_dest }}/install.sh'
     args:
       creates: /etc/python_installed
...
